type Images = {
  [key: string]: string;
};

export const images: Images = {
  main_logo: "/images/logo.png",
  sub_logo: "/images/logo2.png",
  chatting_img: "/images/chatting.png",
  community_img: "/images/community.png",
  mini_room_img: "/images/miniroom.png",
  my_friends_img: "/images/myfriends.png",
  my_page_img: "/images/mypage.png",
  new_friends_img: "/images/newfriends.png",
  dog_img: "/images/dog.png",
  cat_img: "/images/cat.png",
  fox_img: "/images/fox.png",
  rabbit_img: "/images/rabbit.png",
  dino_img: "/images/dino.png",
  bear_img: "/images/bear.png",
  heart_img: "/images/heart.png",
  player_img: "/images/music_player.jpg",
  foot_print_img: "/images/footPrint.png",
  bed_0_img: "/images/x.png",
  bed_1_img: "/images/bed_1.png",
  bed_2_img: "/images/bed_2.png",
  bed_3_img: "/images/bed_3.png",
  drawer_0_img: "/images/x.png",
  drawer_1_img: "/images/drawer_1.png",
  drawer_2_img: "/images/drawer_2.png",
  table_0_img: "/images/x.png",
  table_1_img: "/images/table_1.png",
  table_2_img: "/images/table_2.png",
  sofa_0_img: "/images/x.png",
  sofa_1_img: "/images/sofa_1.png",
  sofa_2_img: "/images/sofa_2.png",
  lamp_0_img: "/images/x.png",
  lamp_1_img: "/images/lamp_1.png",
  lamp_2_img: "/images/lamp_2.png",
  rug_0_img: "/images/x.png",
  rug_1_img: "/images/rug_1.png",
  rug_2_img: "/images/rug_2.png",
  profile_img: "/images/pink_rabbit.png",
  loading_img: "/images/loading.png",
  animate_star: "/images/meteor-rain.gif",
  glasses_0: "/images/x.png",
  glasses_1: "/images/heart_glasses.png",
  glasses_2: "/images/star_glasses.png",
  glasses_3: "/images/alien_glasses.png",
  glasses_4: "/images/circle_glasses.png",
  glasses_5: "/images/my_glasses.png",
  hat_0: "/images/x.png",
  hat_1: "/images/angel_hat.png",
  hat_2: "/images/arab_hat.png",
  hat_3: "/images/magic_hat.png",
  hat_4: "/images/santa_hat.png",
  hat_5: "/images/white_hat.png",
  wing_0: "/images/x.png",
  wing_1: "/images/angel_wing.png",
  wing_2: "/images/bat_wing.png",
  wing_3: "/images/balloon.png",
  wing_4: "/images/vampire_cape.png",
  wing_5: "/images/random.png",
};
