type Images = {
  [key: string]: string;
};

export const images: Images = {
  main_logo: "/images/logo.png",
  sub_logo: "/images/logo2.png",
  chatting_img: "/images/chatting.png",
  community_img: "/images/community.png",
  mini_room_img: "/images/miniroom.png",
  my_friends_img: "/images/myfriends.png",
  my_page_img: "/images/mypage.png",
  new_friends_img: "/images/newfriends.png",
  dog_img: "/images/dog.jpg",
  cat_img: "/images/cat.jpg",
  fox_img: "/images/fox.jpg",
  rabbit_img: "/images/rabbit.jpg",
  dino_img: "/images/dino.jpg",
  bear_img: "/images/bear.jpg",
  heart_img: "/images/heart.png",
  foot_print_img: "/images/footPrint.png",
  bed_1_img: "/images/bed_1.png",
  bed_2_img: "/images/bed_2.png",
  bed_3_img: "/images/bed_3.png",
  drawer_1_img: "/images/drawer_1.png",
  drawer_2_img: "/images/drawer_2.png",
  table_1_img: "/images/table_1.png",
  table_2_img: "/images/table_2.png",
  table_3_img: "/images/table_3.png",
  clock_1_img: "/images/clock_1.png",
  clock_2_img: "/images/clock_2.png",
  lamp_1_img: "/images/lamp_1.png",
  lamp_2_img: "/images/lamp_2.png",
  lamp_3_img: "/images/lamp_3.png",
  profile_img: "/images/pink_rabbit.png",
  loading_img: "/images/loading.png",  
  animate_star: "/images/meteor-rain.gif", 
};
