# Generated by Django 3.2.13 on 2023-03-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_choice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomsong',
            old_name='artist',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='randomsong',
            old_name='genre',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='randomsong',
            old_name='title',
            new_name='Title',
        ),
    ]
