# Generated by Django 3.2.13 on 2023-03-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_choice', '0002_auto_20230316_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomSong',
        ),
    ]
