/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 fox.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    NurbsPath: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube010_1: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
  };
};

export function Fox(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/3D/fox.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[0.07, 2.69, -0.07]}
        rotation={[0, -0.7, 0]}
        scale={[1.21, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
        position={[0.07, 1.27, -0.07]}
        rotation={[0, -0.7, 0]}
        scale={0.68}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.002"]}
        position={[0.07, 2.69, -0.07]}
        rotation={[0, -0.7, 0]}
        scale={[1.21, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Material.002"]}
        position={[0.11, 2.65, -0.11]}
        rotation={[0, -0.7, 0]}
        scale={[1.21, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Material.002"]}
        position={[0.07, 1.27, -0.07]}
        rotation={[0, -0.7, 0]}
        scale={0.68}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials["Material.003"]}
        position={[0.07, 0.31, -0.07]}
        rotation={[0, -0.7, 0]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials["Material.004"]}
        position={[0.07, 0.61, -0.07]}
        rotation={[0, -0.7, 0]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials["Material.003"]}
        position={[-0.48, 2.51, 0.58]}
        rotation={[0, -0.7, 0]}
        scale={[0.07, 0.05, 0.04]}
      />
      <mesh
        geometry={nodes.NurbsPath.geometry}
        material={materials["Material.003"]}
        position={[-0.48, 2.34, 0.58]}
        rotation={[0.11, -0.7, 0.07]}
        scale={0.1}
      />
      <group
        position={[0.68, 0.9, -0.8]}
        rotation={[0, -0.7, 0]}
        scale={[0.34, 0.34, 0.59]}
      >
        <mesh
          geometry={nodes.Cube010.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3D/fox.glb");
