/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 OMZmain_with_png_logo.glb -t
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    writing_desk_writing_desk_0: THREE.Mesh;
    Object_8001: THREE.Mesh;
    Object_4002: THREE.Mesh;
    Cube_1: THREE.SkinnedMesh;
    Cube_2: THREE.SkinnedMesh;
    Cube_3: THREE.SkinnedMesh;
    Cube_4: THREE.SkinnedMesh;
    평면024: THREE.Mesh;
    평면025: THREE.Mesh;
    큐브014: THREE.Mesh;
    큐브015: THREE.Mesh;
    큐브016: THREE.Mesh;
    큐브017: THREE.Mesh;
    큐브018: THREE.Mesh;
    평면026: THREE.Mesh;
    평면027: THREE.Mesh;
    평면028: THREE.Mesh;
    구체006: THREE.Mesh;
    평면029: THREE.Mesh;
    평면030: THREE.Mesh;
    평면031: THREE.Mesh;
    평면032: THREE.Mesh;
    평면033: THREE.Mesh;
    구체007: THREE.Mesh;
    구체008: THREE.Mesh;
    구체009: THREE.Mesh;
    실린더004: THREE.Mesh;
    실린더005: THREE.Mesh;
    구체010: THREE.Mesh;
    평면034: THREE.Mesh;
    평면035: THREE.Mesh;
    평면036: THREE.Mesh;
    평면037: THREE.Mesh;
    평면038: THREE.Mesh;
    실린더006: THREE.Mesh;
    큐브019: THREE.Mesh;
    큐브020: THREE.Mesh;
    큐브021: THREE.Mesh;
    큐브022: THREE.Mesh;
    평면039: THREE.Mesh;
    평면040: THREE.Mesh;
    평면041: THREE.Mesh;
    평면042: THREE.Mesh;
    spine: THREE.Bone;
    neutral_bone: THREE.Bone;
  };
  materials: {
    Material__7: THREE.MeshStandardMaterial;
    writing_desk: THREE.MeshStandardMaterial;
    [".002"]: THREE.MeshStandardMaterial;
    [".001"]: THREE.MeshPhysicalMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["매테리얼.060"]: THREE.MeshStandardMaterial;
    ["매테리얼.061"]: THREE.MeshStandardMaterial;
    ["매테리얼.070"]: THREE.MeshStandardMaterial;
    ["매테리얼.071"]: THREE.MeshStandardMaterial;
    ["매테리얼.072"]: THREE.MeshStandardMaterial;
    ["매테리얼.073"]: THREE.MeshStandardMaterial;
    ["매테리얼.074"]: THREE.MeshStandardMaterial;
    ["매테리얼.075"]: THREE.MeshStandardMaterial;
    ["매테리얼.076"]: THREE.MeshStandardMaterial;
    ["매테리얼.077"]: THREE.MeshStandardMaterial;
    ["매테리얼.078"]: THREE.MeshStandardMaterial;
    ["매테리얼.079"]: THREE.MeshStandardMaterial;
    ["매테리얼.080"]: THREE.MeshStandardMaterial;
    ["매테리얼.081"]: THREE.MeshStandardMaterial;
    ["매테리얼.082"]: THREE.MeshStandardMaterial;
    ["매테리얼.083"]: THREE.MeshStandardMaterial;
    ["매테리얼.084"]: THREE.MeshStandardMaterial;
    ["매테리얼.085"]: THREE.MeshStandardMaterial;
    ["매테리얼.086"]: THREE.MeshStandardMaterial;
    ["매테리얼.087"]: THREE.MeshStandardMaterial;
    ["매테리얼.088"]: THREE.MeshStandardMaterial;
    ["매테리얼.089"]: THREE.MeshStandardMaterial;
    ["매테리얼.090"]: THREE.MeshStandardMaterial;
    ["매테리얼.091"]: THREE.MeshStandardMaterial;
    ["매테리얼.092"]: THREE.MeshStandardMaterial;
    ["매테리얼.093"]: THREE.MeshStandardMaterial;
    ["매테리얼.094"]: THREE.MeshStandardMaterial;
    ["매테리얼.095"]: THREE.MeshStandardMaterial;
    ["매테리얼.096"]: THREE.MeshStandardMaterial;
    ["매테리얼.097"]: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | "엠프티.001Action.007"
  | "metarigAction.001"
  | "엠프티Action.007"
  | "엠프티.002Action.002";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function OMZmain_with_png_logo(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/3D/OMZmain_with_png_logo.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    const action = actions["metarigAction.001"];
    action?.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="엠프티001"
          position={[5.48, 6.79, 6.05]}
          rotation={[1.56, 0.03, -1.37]}
          scale={1.77}
        />
        <group
          name="Sketchfab_model002"
          position={[-0.99, 1.04, 2.62]}
          rotation={[-Math.PI / 2, 0, -0.99]}
          scale={0.66}
        >
          <group name="������objcleanermaterialmergergles002" />
        </group>
        <group
          name="Sketchfab_model003"
          position={[-1.79, 0.31, 3.21]}
          rotation={[-Math.PI / 2, 0, -0.99]}
          scale={0.88}
        >
          <group
            name="������objcleanermaterialmergergles003"
            position={[0, 0, 0.41]}
            scale={0.88}
          />
        </group>
        <group
          name="Sketchfab_model004"
          position={[2.83, 1.03, 4.12]}
          rotation={[-Math.PI / 2, 0, -1.77]}
          scale={0.04}
        >
          <group
            name="JES3S111114_BIGobjcleanergles"
            position={[-44.67, -17.64, 0]}
          >
            <group name="Object_2">
              <mesh
                name="Object_3"
                geometry={nodes.Object_3.geometry}
                material={materials.Material__7}
              />
              <mesh
                name="Object_4"
                geometry={nodes.Object_4.geometry}
                material={materials.Material__7}
              />
              <mesh
                name="Object_5"
                geometry={nodes.Object_5.geometry}
                material={materials.Material__7}
              />
              <mesh
                name="Object_6"
                geometry={nodes.Object_6.geometry}
                material={materials.Material__7}
              />
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model005"
          position={[0.58, 2.52, 0.95]}
          rotation={[-Math.PI / 2, 0, -0.2]}
          scale={0.62}
        >
          <group
            name="writing_deskfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode001">
              <group
                name="writing_desk"
                position={[0, 1.23, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  name="writing_desk_writing_desk_0"
                  geometry={nodes.writing_desk_writing_desk_0.geometry}
                  material={materials.writing_desk}
                  position={[-3.6, 3.99, -0.04]}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model006"
          position={[0.8, 1.01, -0.4]}
          rotation={[-Math.PI / 2, 0, -0.2]}
          scale={4.7}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Lamp_01_3" scale={0.14}>
                <group name="���������_1">
                  <mesh
                    name="Object_8001"
                    geometry={nodes.Object_8001.geometry}
                    material={materials[".002"]}
                    position={[2.52, 0.17, -1.14]}
                    scale={0.5}
                  />
                </group>
                <mesh
                  name="Object_4002"
                  geometry={nodes.Object_4002.geometry}
                  material={materials[".001"]}
                  position={[2.52, 0.17, -1.14]}
                  scale={0.5}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="metarig"
          position={[-1, 1.07, 2.38]}
          rotation={[0, -0.2, 0]}
        >
          <primitive object={nodes.spine} />
          <primitive object={nodes.neutral_bone} />
          <group name="Cube">
            <skinnedMesh
              name="Cube_1"
              geometry={nodes.Cube_1.geometry}
              material={materials["Material.005"]}
              skeleton={nodes.Cube_1.skeleton}
            />
            <skinnedMesh
              name="Cube_2"
              geometry={nodes.Cube_2.geometry}
              material={materials["Material.006"]}
              skeleton={nodes.Cube_2.skeleton}
            />
            <skinnedMesh
              name="Cube_3"
              geometry={nodes.Cube_3.geometry}
              material={materials["Material.007"]}
              skeleton={nodes.Cube_3.skeleton}
            />
            <skinnedMesh
              name="Cube_4"
              geometry={nodes.Cube_4.geometry}
              material={materials["Material.008"]}
              skeleton={nodes.Cube_4.skeleton}
            />
          </group>
        </group>
        <group
          name="엠프티"
          position={[-0.86, 1.33, 2.43]}
          rotation={[0, -0.2, 0]}
        />
        <group
          name="엠프티002"
          position={[2.11, 4.82, -3.98]}
          rotation={[1.55, -0.01, -3.02]}
          scale={0.2}
        />
        <group name="베지어커브" position={[7.92, 0.69, -13.11]} />
        <group name="베지어커브001" position={[7.92, 0.69, -13.11]} />
        <mesh
          name="평면024"
          geometry={nodes.평면024.geometry}
          material={nodes.평면024.material}
          position={[0.8, 0.87, 1.4]}
          rotation={[0, -0.2, 0]}
          scale={4.21}
        />
        <mesh
          name="평면025"
          geometry={nodes.평면025.geometry}
          material={materials["매테리얼.060"]}
          position={[3.03, 0.92, 1.85]}
          rotation={[0, -0.2, 0]}
          scale={[6.48, 4.21, 4.21]}
        />
        <mesh
          name="큐브014"
          geometry={nodes.큐브014.geometry}
          material={materials["매테리얼.061"]}
          position={[0.8, 0.87, 1.4]}
          rotation={[0, -0.2, 0]}
          scale={4.21}
        />
        <mesh
          name="큐브015"
          geometry={nodes.큐브015.geometry}
          material={materials["매테리얼.070"]}
          position={[2.76, 2.69, 1.12]}
          rotation={[0, -0.2, 0]}
          scale={[2.39, 1.32, 0.55]}
        />
        <mesh
          name="큐브016"
          geometry={nodes.큐브016.geometry}
          material={materials["매테리얼.071"]}
          position={[2.55, 3.67, 2.15]}
          rotation={[0, -0.2, 0]}
          scale={[2.39, 0.62, 0.35]}
        />
        <mesh
          name="큐브017"
          geometry={nodes.큐브017.geometry}
          material={materials["매테리얼.072"]}
          position={[2.55, 2.86, 2.15]}
          rotation={[0, -0.2, 0]}
          scale={[2.39, 0.62, 0.35]}
        />
        <mesh
          name="큐브018"
          geometry={nodes.큐브018.geometry}
          material={materials["매테리얼.073"]}
          position={[0.8, 0.87, 1.4]}
          rotation={[0, -0.2, 0]}
          scale={4.21}
        />
        <mesh
          name="평면026"
          geometry={nodes.평면026.geometry}
          material={materials["매테리얼.074"]}
          position={[3.5, 1.91, 0.3]}
          rotation={[0, -0.2, 0]}
          scale={[0.91, 1.48, 1.48]}
        />
        <mesh
          name="평면027"
          geometry={nodes.평면027.geometry}
          material={materials["매테리얼.075"]}
          position={[3.5, 0.94, 0.3]}
          rotation={[0, -0.2, 0]}
          scale={2.86}
        />
        <mesh
          name="평면028"
          geometry={nodes.평면028.geometry}
          material={materials["매테리얼.076"]}
          position={[2.25, 1.07, 1.48]}
          rotation={[0, -0.2, 0]}
          scale={[-0.09, -0.15, -0.09]}
        />
        <mesh
          name="구체006"
          geometry={nodes.구체006.geometry}
          material={materials["매테리얼.077"]}
          position={[2.26, 2.73, 1.48]}
          rotation={[0, -0.2, 0]}
          scale={0.2}
        />
        <mesh
          name="평면029"
          geometry={nodes.평면029.geometry}
          material={nodes.평면029.material}
          position={[3.5, 2.11, 0.3]}
          rotation={[0, -0.2, 0]}
          scale={[0.91, 1.48, 1.21]}
        />
        <mesh
          name="평면030"
          geometry={nodes.평면030.geometry}
          material={materials["매테리얼.078"]}
          position={[3.46, 2.11, 0.46]}
          rotation={[0, -0.2, 0]}
          scale={[0.91, 1.48, 1.5]}
        />
        <mesh
          name="평면031"
          geometry={nodes.평면031.geometry}
          material={materials["매테리얼.079"]}
          position={[3.68, 2.26, -0.62]}
          rotation={[0, -0.2, 0]}
          scale={[0.34, 1.06, 0.21]}
        />
        <mesh
          name="평면032"
          geometry={nodes.평면032.geometry}
          material={materials["매테리얼.080"]}
          position={[1.56, 1.88, -1.35]}
          rotation={[0, -0.2, 0]}
          scale={[0.65, 2, 0.72]}
        />
        <mesh
          name="평면033"
          geometry={nodes.평면033.geometry}
          material={materials["매테리얼.081"]}
          position={[0.89, 1.77, -0.86]}
          rotation={[0, -0.2, 0]}
          scale={[0.12, 2.32, 0.13]}
        />
        <mesh
          name="구체007"
          geometry={nodes.구체007.geometry}
          material={nodes.구체007.material}
          position={[1.39, 1.73, -0.5]}
          rotation={[0, -0.2, 0]}
          scale={0.04}
        />
        <mesh
          name="구체008"
          geometry={nodes.구체008.geometry}
          material={nodes.구체008.material}
          position={[1.31, 1.39, -0.1]}
          rotation={[0, -0.2, 0]}
          scale={0.04}
        />
        <mesh
          name="구체009"
          geometry={nodes.구체009.geometry}
          material={materials["매테리얼.082"]}
          position={[1.51, 3.2, -1.4]}
          rotation={[0, -0.2, 0]}
          scale={0.25}
        />
        <mesh
          name="실린더004"
          geometry={nodes.실린더004.geometry}
          material={materials["매테리얼.083"]}
          position={[1.49, 2.73, -1.32]}
          rotation={[0, -0.2, 0]}
          scale={0.37}
        />
        <mesh
          name="실린더005"
          geometry={nodes.실린더005.geometry}
          material={materials["매테리얼.084"]}
          position={[1.15, 5.58, -2.26]}
          rotation={[0, -0.2, 0]}
          scale={0.2}
        >
          <mesh
            name="구체010"
            geometry={nodes.구체010.geometry}
            material={materials["매테리얼.085"]}
            position={[0, 1.62, 0]}
            scale={[1.26, 2.18, 1.26]}
          />
        </mesh>
        <mesh
          name="평면034"
          geometry={nodes.평면034.geometry}
          material={materials["매테리얼.086"]}
          position={[-0.26, 5.4, -2.61]}
          rotation={[0, -0.61, 0]}
          scale={[0.25, 0.33, 0.33]}
        />
        <mesh
          name="평면035"
          geometry={nodes.평면035.geometry}
          material={materials["매테리얼.087"]}
          position={[-0.26, 5.49, -2.61]}
          rotation={[0, -0.21, 0]}
          scale={[0.25, 0.33, 0.33]}
        />
        <mesh
          name="평면036"
          geometry={nodes.평면036.geometry}
          material={materials["매테리얼.088"]}
          position={[5, 3.74, 1.57]}
          rotation={[0, -0.2, Math.PI / 2]}
          scale={[0.58, 0.49, 0.53]}
        />
        <mesh
          name="평면037"
          geometry={nodes.평면037.geometry}
          material={materials["매테리얼.088"]}
          position={[4.79, 4.14, 2.6]}
          rotation={[0, -0.2, Math.PI / 2]}
          scale={[0.3, 0.3, 0.32]}
        />
        <mesh
          name="평면038"
          geometry={nodes.평면038.geometry}
          material={materials["매테리얼.088"]}
          position={[4.79, 3.36, 2.6]}
          rotation={[0, -0.2, Math.PI / 2]}
          scale={[0.3, 0.3, 0.32]}
        />
        <mesh
          name="실린더006"
          geometry={nodes.실린더006.geometry}
          material={materials["매테리얼.089"]}
          position={[-2.28, 1.92, -1.4]}
          rotation={[-Math.PI, 0.16, -Math.PI]}
          scale={[0.08, 0.77, 0.08]}
        />
        <mesh
          name="큐브019"
          geometry={nodes.큐브019.geometry}
          material={materials["매테리얼.090"]}
          position={[-1.63, 3.09, -2.22]}
          rotation={[-3.14, 0.13, -0.29]}
          scale={[0.08, 0.29, 0.3]}
        />
        <mesh
          name="큐브020"
          geometry={nodes.큐브020.geometry}
          material={materials["매테리얼.091"]}
          position={[-1.87, 3.09, -2.26]}
          rotation={[-Math.PI, 0.16, 0]}
          scale={[0.08, 0.29, 0.3]}
        />
        <mesh
          name="큐브021"
          geometry={nodes.큐브021.geometry}
          material={materials["매테리얼.092"]}
          position={[-2.03, 3.09, -2.29]}
          rotation={[-Math.PI, 0.16, 0]}
          scale={[0.08, 0.29, 0.3]}
        />
        <mesh
          name="큐브022"
          geometry={nodes.큐브022.geometry}
          material={materials["매테리얼.093"]}
          position={[-1.79, 3.14, -2.29]}
          rotation={[-Math.PI, 0.16, -Math.PI]}
          scale={[0.36, 0.38, 0.3]}
        />
        <mesh
          name="평면039"
          geometry={nodes.평면039.geometry}
          material={materials["매테리얼.094"]}
          position={[-1.71, 3.35, -2.24]}
          rotation={[-3.14, 0.13, 2.85]}
          scale={[0.07, 0.3, 0.26]}
        />
        <mesh
          name="평면040"
          geometry={nodes.평면040.geometry}
          material={materials["매테리얼.095"]}
          position={[-1.86, 3.36, -2.27]}
          rotation={[-Math.PI, 0.16, -Math.PI]}
          scale={[0.07, 0.3, 0.26]}
        />
        <mesh
          name="평면041"
          geometry={nodes.평면041.geometry}
          material={materials["매테리얼.096"]}
          position={[-2.02, 3.36, -2.29]}
          rotation={[-Math.PI, 0.16, -Math.PI]}
          scale={[0.07, 0.3, 0.26]}
        />
        <mesh
          name="평면042"
          geometry={nodes.평면042.geometry}
          material={materials["매테리얼.097"]}
          position={[-1.02, 2.75, -1.77]}
          rotation={[-Math.PI, 0.16, -Math.PI]}
          scale={[1.37, 0.53, 0.78]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3D/OMZmain_with_png_logo.glb");
