/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 miniroomBeta3.glb -t
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Books_Books_0: THREE.Mesh;
    Boxes_B_Tranaparency_0: THREE.Mesh;
    Boxes_Boxes_0: THREE.Mesh;
    Cell_phone_Cell_phone_0: THREE.Mesh;
    Cell_phone_Cell_screen_0: THREE.Mesh;
    Desk_Desk_0: THREE.Mesh;
    Dish_Cup_0: THREE.Mesh;
    Eraser_Eraser_0: THREE.Mesh;
    Keyboard_wire_WIre_0: THREE.Mesh;
    Mouse_wire_WIre_0: THREE.Mesh;
    Mousepad_Mousepad_0: THREE.Mesh;
    Notebook_Notebook_0: THREE.Mesh;
    Notebook_wire_WIre_0: THREE.Mesh;
    Paper_Paper_0: THREE.Mesh;
    PC_Keyboard_Keyboard_light_0: THREE.Mesh;
    PC_Keyboard_PC_Keyboard_0: THREE.Mesh;
    PC_Monitor_PC_Monitor_0: THREE.Mesh;
    PC_Monitor_PC_Screen_0: THREE.Mesh;
    PC_Mouse_PC_Mouse_0: THREE.Mesh;
    PC_Speaker_PC_Speakers_0: THREE.Mesh;
    Pen_Pen_0: THREE.Mesh;
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4001: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6001: THREE.Mesh;
    Object_7001: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9001: THREE.Mesh;
    Object_6002: THREE.Mesh;
    Object_8001: THREE.Mesh;
    Object_4002: THREE.Mesh;
    평면: THREE.Mesh;
    큐브: THREE.Mesh;
    큐브001: THREE.Mesh;
    평면001: THREE.Mesh;
    실린더: THREE.Mesh;
    큐브002: THREE.Mesh;
    큐브003: THREE.Mesh;
    평면002: THREE.Mesh;
    평면003: THREE.Mesh;
    큐브004: THREE.Mesh;
    평면004: THREE.Mesh;
    큐브005: THREE.Mesh;
    구체: THREE.Mesh;
    실린더001: THREE.Mesh;
    원뿔: THREE.Mesh;
    평면005: THREE.Mesh;
    평면006: THREE.Mesh;
    큐브006: THREE.Mesh;
    평면007: THREE.Mesh;
    평면008: THREE.Mesh;
    큐브007: THREE.Mesh;
    큐브008: THREE.Mesh;
  };
  materials: {
    Books: THREE.MeshStandardMaterial;
    B_Tranaparency: THREE.MeshStandardMaterial;
    Boxes: THREE.MeshStandardMaterial;
    Cell_phone: THREE.MeshStandardMaterial;
    Cell_screen: THREE.MeshStandardMaterial;
    Desk: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    Eraser: THREE.MeshStandardMaterial;
    WIre: THREE.MeshStandardMaterial;
    Mousepad: THREE.MeshStandardMaterial;
    Notebook: THREE.MeshStandardMaterial;
    Paper: THREE.MeshStandardMaterial;
    Keyboard_light: THREE.MeshStandardMaterial;
    material_0: THREE.MeshStandardMaterial;
    PC_Monitor: THREE.MeshStandardMaterial;
    PC_Screen: THREE.MeshStandardMaterial;
    PC_Mouse: THREE.MeshStandardMaterial;
    PC_Speakers: THREE.MeshStandardMaterial;
    material_1: THREE.MeshStandardMaterial;
    lambert3SG: THREE.MeshStandardMaterial;
    lambert6SG: THREE.MeshStandardMaterial;
    lambert7SG: THREE.MeshStandardMaterial;
    lambert4SG: THREE.MeshStandardMaterial;
    lambert5SG: THREE.MeshStandardMaterial;
    lambert8SG: THREE.MeshStandardMaterial;
    lambert9SG: THREE.MeshStandardMaterial;
    ["material.001"]: THREE.MeshStandardMaterial;
    [".002"]: THREE.MeshStandardMaterial;
    [".001"]: THREE.MeshPhysicalMaterial;
    매테리얼: THREE.MeshStandardMaterial;
    ["매테리얼.002"]: THREE.MeshStandardMaterial;
    ["매테리얼.001"]: THREE.MeshStandardMaterial;
    ["매테리얼.004"]: THREE.MeshStandardMaterial;
    ["매테리얼.003"]: THREE.MeshStandardMaterial;
    ["매테리얼.005"]: THREE.MeshStandardMaterial;
    ["매테리얼.007"]: THREE.MeshStandardMaterial;
    ["매테리얼.006"]: THREE.MeshStandardMaterial;
    ["매테리얼.008"]: THREE.MeshStandardMaterial;
    ["매테리얼.009"]: THREE.MeshStandardMaterial;
    ["매테리얼.010"]: THREE.MeshStandardMaterial;
    ["매테리얼.011"]: THREE.MeshStandardMaterial;
    ["매테리얼.015"]: THREE.MeshStandardMaterial;
    ["매테리얼.016"]: THREE.MeshStandardMaterial;
    ["매테리얼.013"]: THREE.MeshStandardMaterial;
    ["매테리얼.014"]: THREE.MeshStandardMaterial;
    ["매테리얼.012"]: THREE.MeshStandardMaterial;
  };
};

interface Item {
  [key: string]: string;
}
type Props = {
  position: number[];
  itemStatus?: Item;
};

export function MiniroomBeta3({ position, itemStatus }: Props) {
  const { nodes, materials } = useGLTF(
    "/MiniRoom/miniroomBeta3.glb"
  ) as GLTFResult;

  const selectTable = () => {
    switch (itemStatus?.table) {
      case "1":
        return (
          <>
            <mesh
              geometry={nodes.평면001.geometry}
              material={materials["매테리얼.004"]}
              position={[-7.97, 6.03, -10.58]}
              rotation={[Math.PI, -0.04, Math.PI]}
              scale={[4.5, 1.74, 2.57]}
            />
            <mesh
              geometry={nodes.실린더.geometry}
              material={materials["매테리얼.003"]}
              position={[-11.79, 3.27, -8.57]}
              rotation={[Math.PI, -0.04, Math.PI]}
              scale={[0.25, 2.54, 0.25]}
            />
            <mesh
              geometry={nodes.큐브002.geometry}
              material={materials["매테리얼.005"]}
              position={[-10.79, 7.32, -11.74]}
              rotation={[Math.PI, -0.04, Math.PI]}
              scale={[1.17, 1.26, 1]}
            />
            <mesh
              geometry={nodes.큐브003.geometry}
              material={materials["매테리얼.007"]}
              position={[-11.55, 7.13, -11.59]}
              rotation={[Math.PI, -0.04, 0]}
              scale={[0.25, 0.94, 1]}
            />
            <mesh
              geometry={nodes.평면002.geometry}
              material={materials["매테리얼.006"]}
              position={[-11.55, 8.03, -11.61]}
              rotation={[Math.PI, -0.04, Math.PI]}
              scale={[0.24, 1, 0.84]}
            />
            <mesh
              geometry={nodes.평면003.geometry}
              material={materials["매테리얼.008"]}
              position={[-11.01, 8.03, -11.64]}
              rotation={[Math.PI, -0.04, Math.PI]}
              scale={[0.24, 1, 0.84]}
            />
            <mesh
              geometry={nodes.큐브004.geometry}
              material={materials["매테리얼.009"]}
              position={[-11.02, 7.13, -11.61]}
              rotation={[Math.PI, -0.04, 0]}
              scale={[0.25, 0.94, 1]}
            />
            <mesh
              geometry={nodes.평면004.geometry}
              material={materials["매테리얼.010"]}
              position={[-10.49, 8.01, -11.65]}
              rotation={[-3.14, -0.07, 2.85]}
              scale={[0.24, 1, 0.84]}
            />
            <mesh
              geometry={nodes.큐브005.geometry}
              material={materials["매테리얼.011"]}
              position={[-10.25, 7.15, -11.65]}
              rotation={[-3.14, -0.07, -0.29]}
              scale={[0.25, 0.94, 1]}
            />
          </>
        );
      case "2":
        return (
          <group
            position={[-7.87, 0, -10.49]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.03, 0.02, 0.03]}
          >
            <group rotation={[Math.PI / 2, 0, 0]}>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  geometry={nodes.Boxes_B_Tranaparency_0.geometry}
                  material={materials.B_Tranaparency}
                />
                <mesh
                  geometry={nodes.Boxes_Boxes_0.geometry}
                  material={materials.Boxes}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  geometry={nodes.Cell_phone_Cell_phone_0.geometry}
                  material={materials.Cell_phone}
                />
                <mesh
                  geometry={nodes.Cell_phone_Cell_screen_0.geometry}
                  material={materials.Cell_screen}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  geometry={nodes.PC_Keyboard_Keyboard_light_0.geometry}
                  material={materials.Keyboard_light}
                />
                <mesh
                  geometry={nodes.PC_Keyboard_PC_Keyboard_0.geometry}
                  material={materials.material_0}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  geometry={nodes.PC_Monitor_PC_Monitor_0.geometry}
                  material={materials.PC_Monitor}
                />
                <mesh
                  geometry={nodes.PC_Monitor_PC_Screen_0.geometry}
                  material={materials.PC_Screen}
                />
              </group>
              <mesh
                geometry={nodes.Books_Books_0.geometry}
                material={materials.Books}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                geometry={nodes.Desk_Desk_0.geometry}
                material={materials.Desk}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                geometry={nodes.Dish_Cup_0.geometry}
                material={materials.material}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                geometry={nodes.Eraser_Eraser_0.geometry}
                material={materials.Eraser}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                geometry={nodes.Keyboard_wire_WIre_0.geometry}
                material={materials.WIre}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                geometry={nodes.Mouse_wire_WIre_0.geometry}
                material={materials.WIre}
                position={[0, 0, -47.15]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                geometry={nodes.Mousepad_Mousepad_0.geometry}
                material={materials.Mousepad}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                geometry={nodes.Notebook_Notebook_0.geometry}
                material={materials.Notebook}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                geometry={nodes.Notebook_wire_WIre_0.geometry}
                material={materials.WIre}
                position={[0, 0, 290.97]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                geometry={nodes.Paper_Paper_0.geometry}
                material={materials.Paper}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                geometry={nodes.PC_Mouse_PC_Mouse_0.geometry}
                material={materials.PC_Mouse}
                scale={100}
              />
              <mesh
                geometry={nodes.PC_Speaker_PC_Speakers_0.geometry}
                material={materials.PC_Speakers}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                geometry={nodes.Pen_Pen_0.geometry}
                material={materials.material_1}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
            </group>
          </group>
        );
    }
  };

  const selectLamp = () => {
    switch (itemStatus?.lamp) {
      case "1":
        return (
          <>
            <mesh
              geometry={nodes.구체.geometry}
              material={materials["매테리얼.015"]}
              position={[-3.38, 11.99, -11.29]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={0.52}
            />
            <mesh
              geometry={nodes.실린더001.geometry}
              material={materials["매테리얼.016"]}
              position={[-0.94, 4.31, -11.24]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={0.1}
            />
            <mesh
              geometry={nodes.원뿔.geometry}
              material={materials["매테리얼.013"]}
              position={[-2.94, 12.7, -11.29]}
              rotation={[-Math.PI, 0, -2.62]}
            />
            <mesh
              geometry={nodes.평면005.geometry}
              material={materials["매테리얼.014"]}
              position={[-0.94, 1.02, -11.24]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={1.75}
            />
          </>
        );
      case "2":
        return (
          <group
            position={[0, 0.82, -11.18]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={9.36}
          >
            <group rotation={[Math.PI / 2, 0, 0]}>
              <group scale={0.14}>
                <mesh
                  geometry={nodes.Object_4002.geometry}
                  material={materials[".001"]}
                />
                <mesh
                  geometry={nodes.Object_6002.geometry}
                  material={materials["material.001"]}
                  position={[0, 7.34, 0]}
                  scale={0.29}
                />
                <mesh
                  geometry={nodes.Object_8001.geometry}
                  material={materials[".002"]}
                />
              </group>
            </group>
          </group>
        );
    }
  };

  const selectBed = () => {
    switch (itemStatus?.bed) {
      case "1":
        return (
          <>
            <mesh
              geometry={nodes.평면006.geometry}
              material={nodes.평면006.material}
              position={[8.36, 3.82, -2.87]}
              rotation={[0, 0, -Math.PI]}
              scale={[-5, -1, -7.5]}
            />
            <mesh
              geometry={nodes.큐브006.geometry}
              material={materials["매테리얼.012"]}
              position={[8.36, 1.73, 5.79]}
              scale={[5, 1, 1]}
            />
            <mesh
              geometry={nodes.평면007.geometry}
              material={nodes.평면007.material}
              position={[8.36, 4.85, -2.87]}
              rotation={[0, 0, -Math.PI]}
              scale={[-5, -1, -7.5]}
            />
            <mesh
              geometry={nodes.평면008.geometry}
              material={materials["매테리얼.012"]}
              position={[8.36, 2.77, -2.87]}
              scale={[5, 1, 8]}
            />
            <mesh
              geometry={nodes.큐브007.geometry}
              material={materials["매테리얼.012"]}
              position={[8.36, 4.67, -1.43]}
              scale={[5.29, 0.81, 5.6]}
            />
            <mesh
              geometry={nodes.큐브008.geometry}
              material={materials["매테리얼.012"]}
              position={[8.36, 5.58, -8.78]}
              scale={[1.63, 0.53, 1]}
            />
          </>
        );
      case "2":
        return (
          <group
            position={[8.37, 0.7, -3.63]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[6.29, 7.63, 6.29]}
          >
            <mesh
              geometry={nodes.Object_2.geometry}
              material={materials.lambert3SG}
            />
            <mesh
              geometry={nodes.Object_3.geometry}
              material={materials.lambert6SG}
            />
            <mesh
              geometry={nodes.Object_4001.geometry}
              material={materials.lambert7SG}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials.lambert4SG}
            />
            <mesh
              geometry={nodes.Object_6001.geometry}
              material={materials.lambert5SG}
            />
            <mesh
              geometry={nodes.Object_7001.geometry}
              material={materials.lambert5SG}
            />
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials.lambert8SG}
            />
            <mesh
              geometry={nodes.Object_9001.geometry}
              material={materials.lambert9SG}
            />
          </group>
        );
    }
  };

  const props: any = { position };
  return (
    <group {...props} dispose={null}>
      {selectTable()}
      {selectLamp()}
      {selectBed()}
      <mesh
        geometry={nodes.평면.geometry}
        material={materials.매테리얼}
        scale={[15, 14.43, 15]}
      />
      <mesh
        geometry={nodes.큐브.geometry}
        material={materials["매테리얼.002"]}
        position={[0, 12.87, -14.5]}
        scale={[15, 12.76, 0.5]}
      />
      <mesh
        geometry={nodes.큐브001.geometry}
        material={materials["매테리얼.001"]}
        position={[14.5, 12.87, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[15, 12.76, 0.5]}
      />
    </group>
  );
}

useGLTF.preload("/MiniRoom/miniroomBeta3.glb");
