/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 miniroomBetaFinal.glb -t
*/

import * as THREE from "three";
import React, { useRef, useState } from "react";
import { GLTF } from "three-stdlib";
import { DirectionalLightHelper } from "three";
import { useGLTF, useAnimations, useHelper } from "@react-three/drei";

type GLTFResult = GLTF & {
  nodes: {
    Object_8001: THREE.Mesh;
    Object_4002: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    BedInner_Material003_0: THREE.Mesh;
    BedPillow_Material004_0: THREE.Mesh;
    BedSheet_Material005_0: THREE.Mesh;
    BedSheet_Material006_0: THREE.Mesh;
    Bed_Material002_0: THREE.Mesh;
    Bed_Material003_0: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_2001: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_3001: THREE.Mesh;
    Object_4001: THREE.Mesh;
    Object_5001: THREE.Mesh;
    Object_6001: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    defaultMaterial: THREE.Mesh;
    back2_aiStandardSurface1_0: THREE.Mesh;
    back_bone_aiStandardSurface1_0: THREE.Mesh;
    adjustment_aiStandardSurface1_0: THREE.Mesh;
    Bolt_aiStandardSurface1_0: THREE.Mesh;
    Bolt1_aiStandardSurface1_0: THREE.Mesh;
    Bolt2_aiStandardSurface1_0: THREE.Mesh;
    Bolt3_aiStandardSurface1_0: THREE.Mesh;
    pCube6_aiStandardSurface1_0: THREE.Mesh;
    pCube9_aiStandardSurface1_0: THREE.Mesh;
    pCylinder10_aiStandardSurface1_0: THREE.Mesh;
    pCylinder14_aiStandardSurface1_0: THREE.Mesh;
    polySurface11_aiStandardSurface1_0: THREE.Mesh;
    pPlane3_aiStandardSurface1_0: THREE.Mesh;
    butt_aiStandardSurface1_0: THREE.Mesh;
    L_handle_aiStandardSurface1_0: THREE.Mesh;
    R_handle_aiStandardSurface1_0: THREE.Mesh;
    polySurface24_aiStandardSurface1_0: THREE.Mesh;
    polySurface43_aiStandardSurface1_0: THREE.Mesh;
    wheel_aiStandardSurface1_0: THREE.Mesh;
    wheel2_aiStandardSurface1_0: THREE.Mesh;
    wheel3_aiStandardSurface1_0: THREE.Mesh;
    wheel4_aiStandardSurface1_0: THREE.Mesh;
    desk2: THREE.Mesh;
    구체001: THREE.Mesh;
    구체002: THREE.Mesh;
    구체003: THREE.Mesh;
    실린더: THREE.Mesh;
    평면009: THREE.Mesh;
    평면010: THREE.Mesh;
    구체: THREE.Mesh;
    평면003: THREE.Mesh;
    평면004: THREE.Mesh;
    평면005: THREE.Mesh;
    평면006: THREE.Mesh;
    평면007: THREE.Mesh;
    평면008: THREE.Mesh;
    실린더002: THREE.Mesh;
    큐브005: THREE.Mesh;
    큐브006: THREE.Mesh;
    큐브007: THREE.Mesh;
    큐브008: THREE.Mesh;
    평면016: THREE.Mesh;
    평면017: THREE.Mesh;
    평면018: THREE.Mesh;
    평면019: THREE.Mesh;
    구체005: THREE.Mesh;
    구체006: THREE.Mesh;
    베지어커브: THREE.Mesh;
    베지어커브001: THREE.Mesh;
    베지어커브002: THREE.Mesh;
    큐브009: THREE.Mesh;
    큐브010: THREE.Mesh;
    큐브011: THREE.Mesh;
    큐브012: THREE.Mesh;
    큐브013: THREE.Mesh;
    큐브014: THREE.Mesh;
    큐브015: THREE.Mesh;
    큐브016: THREE.Mesh;
    큐브017: THREE.Mesh;
    큐브018: THREE.Mesh;
    큐브019: THREE.Mesh;
    큐브020: THREE.Mesh;
    큐브021: THREE.Mesh;
    큐브022: THREE.Mesh;
    큐브023: THREE.Mesh;
    큐브024: THREE.Mesh;
    큐브025: THREE.Mesh;
    큐브026: THREE.Mesh;
    큐브027: THREE.Mesh;
    큐브028: THREE.Mesh;
    큐브029: THREE.Mesh;
    큐브030: THREE.Mesh;
    큐브031: THREE.Mesh;
    큐브032: THREE.Mesh;
    큐브033: THREE.Mesh;
    큐브034: THREE.Mesh;
    큐브035: THREE.Mesh;
    큐브036: THREE.Mesh;
    큐브037: THREE.Mesh;
    큐브038: THREE.Mesh;
    큐브039: THREE.Mesh;
    큐브040: THREE.Mesh;
    큐브041: THREE.Mesh;
    큐브042: THREE.Mesh;
    큐브043: THREE.Mesh;
    큐브044: THREE.Mesh;
    큐브045: THREE.Mesh;
    큐브046: THREE.Mesh;
    큐브047: THREE.Mesh;
    큐브048: THREE.Mesh;
    큐브049: THREE.Mesh;
    큐브050: THREE.Mesh;
    큐브051: THREE.Mesh;
    큐브052: THREE.Mesh;
    큐브053: THREE.Mesh;
    큐브054: THREE.Mesh;
    큐브055: THREE.Mesh;
    큐브056: THREE.Mesh;
    큐브057: THREE.Mesh;
    큐브058: THREE.Mesh;
    큐브059: THREE.Mesh;
    큐브060: THREE.Mesh;
    큐브061: THREE.Mesh;
    큐브062: THREE.Mesh;
    큐브063: THREE.Mesh;
    큐브064: THREE.Mesh;
    큐브065: THREE.Mesh;
    큐브066: THREE.Mesh;
    큐브067: THREE.Mesh;
    큐브068: THREE.Mesh;
    큐브069: THREE.Mesh;
    큐브070: THREE.Mesh;
    큐브071: THREE.Mesh;
    큐브072: THREE.Mesh;
    큐브073: THREE.Mesh;
    큐브074: THREE.Mesh;
    큐브075_1: THREE.Mesh;
    큐브075_2: THREE.Mesh;
    큐브076_1: THREE.Mesh;
    큐브076_2: THREE.Mesh;
    평면: THREE.Mesh;
    평면020: THREE.Mesh;
    평면021: THREE.Mesh;
    평면022: THREE.Mesh;
    평면024_1: THREE.Mesh;
    평면024_2: THREE.Mesh;
    실린더003: THREE.Mesh;
    실린더004: THREE.Mesh;
    실린더005: THREE.Mesh;
    실린더006: THREE.Mesh;
    실린더007: THREE.Mesh;
    큐브077: THREE.Mesh;
    큐브078: THREE.Mesh;
    큐브079: THREE.Mesh;
    큐브080: THREE.Mesh;
    평면024: THREE.Mesh;
    평면025: THREE.Mesh;
    평면026: THREE.Mesh;
    구체008: THREE.Mesh;
    실린더008: THREE.Mesh;
    원뿔: THREE.Mesh;
    평면027: THREE.Mesh;
    실린더001: THREE.Mesh;
    구체004_1: THREE.Mesh;
    큐브: THREE.Mesh;
    큐브001: THREE.Mesh;
    큐브004: THREE.Mesh;
    평면001: THREE.Mesh;
    평면002: THREE.Mesh;
    평면011: THREE.Mesh;
    평면012: THREE.Mesh;
    평면013: THREE.Mesh;
    평면014: THREE.Mesh;
    평면015: THREE.Mesh;
    큐브002: THREE.Mesh;
    큐브003: THREE.Mesh;
    평면028: THREE.Mesh;
  };
  materials: {
    [".002"]: THREE.MeshStandardMaterial;
    [".001"]: THREE.MeshPhysicalMaterial;
    Material__7: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.046"]: THREE.MeshStandardMaterial;
    ["Material.040"]: THREE.MeshStandardMaterial;
    ["Material.041"]: THREE.MeshStandardMaterial;
    ["Material.042"]: THREE.MeshStandardMaterial;
    ["Material.043"]: THREE.MeshStandardMaterial;
    ["Material.044"]: THREE.MeshStandardMaterial;
    ["Material.045"]: THREE.MeshStandardMaterial;
    Chair: THREE.MeshStandardMaterial;
    aiStandardSurface1: THREE.MeshStandardMaterial;
    ["writing_desk.001"]: THREE.MeshStandardMaterial;
    ["매테리얼.008"]: THREE.MeshStandardMaterial;
    ["매테리얼.007"]: THREE.MeshStandardMaterial;
    ["매테리얼.009"]: THREE.MeshStandardMaterial;
    ["매테리얼.010"]: THREE.MeshStandardMaterial;
    ["매테리얼.002"]: THREE.MeshStandardMaterial;
    ["매테리얼.005"]: THREE.MeshStandardMaterial;
    ["매테리얼.003"]: THREE.MeshStandardMaterial;
    ["매테리얼.001"]: THREE.MeshStandardMaterial;
    매테리얼: THREE.MeshStandardMaterial;
    ["매테리얼.004"]: THREE.MeshStandardMaterial;
    ["매테리얼.029"]: THREE.MeshStandardMaterial;
    ["매테리얼.025"]: THREE.MeshStandardMaterial;
    ["매테리얼.026"]: THREE.MeshStandardMaterial;
    ["매테리얼.027"]: THREE.MeshStandardMaterial;
    ["매테리얼.028"]: THREE.MeshStandardMaterial;
    ["매테리얼.017"]: THREE.MeshStandardMaterial;
    ["매테리얼.022"]: THREE.MeshStandardMaterial;
    ["매테리얼.023"]: THREE.MeshStandardMaterial;
    ["매테리얼.024"]: THREE.MeshStandardMaterial;
    ["매테리얼.035"]: THREE.MeshStandardMaterial;
    ["매테리얼.032"]: THREE.MeshStandardMaterial;
    ["매테리얼.034"]: THREE.MeshStandardMaterial;
    ["매테리얼.036"]: THREE.MeshStandardMaterial;
    ["매테리얼.037"]: THREE.MeshStandardMaterial;
    ["매테리얼.038"]: THREE.MeshStandardMaterial;
    ["매테리얼.031"]: THREE.MeshStandardMaterial;
    ["매테리얼.039"]: THREE.MeshStandardMaterial;
    ["매테리얼.030"]: THREE.MeshStandardMaterial;
    ["매테리얼.033"]: THREE.MeshStandardMaterial;
    ["매테리얼.040"]: THREE.MeshStandardMaterial;
    ["매테리얼.041"]: THREE.MeshStandardMaterial;
    ["매테리얼.042"]: THREE.MeshStandardMaterial;
    ["매테리얼.046"]: THREE.MeshStandardMaterial;
    ["매테리얼.043"]: THREE.MeshStandardMaterial;
    ["매테리얼.044"]: THREE.MeshStandardMaterial;
    ["매테리얼.045"]: THREE.MeshStandardMaterial;
    ["매테리얼.047"]: THREE.MeshStandardMaterial;
    ["매테리얼.054"]: THREE.MeshStandardMaterial;
    ["매테리얼.053"]: THREE.MeshStandardMaterial;
    ["매테리얼.052"]: THREE.MeshStandardMaterial;
    ["매테리얼.051"]: THREE.MeshStandardMaterial;
    ["매테리얼.011"]: THREE.MeshStandardMaterial;
    ["매테리얼.012"]: THREE.MeshStandardMaterial;
    ["매테리얼.021"]: THREE.MeshStandardMaterial;
    ["매테리얼.016"]: THREE.MeshStandardMaterial;
    ["매테리얼.013"]: THREE.MeshStandardMaterial;
    ["매테리얼.006"]: THREE.MeshStandardMaterial;
    ["매테리얼.015"]: THREE.MeshStandardMaterial;
    ["매테리얼.014"]: THREE.MeshStandardMaterial;
    ["매테리얼.018"]: THREE.MeshStandardMaterial;
    ["매테리얼.020"]: THREE.MeshStandardMaterial;
    ["매테리얼.019"]: THREE.MeshStandardMaterial;
  };
};

interface Item {
  [key: string]: string;
}
type Props = {
  position: number[];
  itemStatus?: Item;
};

export function MiniroomBetaFinal({ position, itemStatus }: Props) {
  const { nodes, materials } = useGLTF(
    "/MiniRoom/miniroomBetaFinal.glb"
  ) as GLTFResult;

  const selectTable = () => {
    switch (itemStatus?.table) {
      case "1":
        return (
          <>
            {" "}
            <group
              position={[-2.08, 2.17, -1.34]}
              rotation={[-Math.PI / 2, 0, -2.24]}
              scale={1.18}
            >
              <mesh
                geometry={nodes.defaultMaterial.geometry}
                material={materials.Chair}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            {/* 책상 1 씨작 */}
            <mesh
              geometry={nodes.실린더002.geometry}
              material={materials["매테리얼.029"]}
              position={[-3.58, 1.97, -1.65]}
              rotation={[Math.PI, -0.04, Math.PI]}
              scale={[0.09, 0.91, 0.09]}
            />
            <mesh
              geometry={nodes.큐브005.geometry}
              material={materials["매테리얼.025"]}
              position={[-3.02, 3.36, -2.75]}
              rotation={[-3.14, -0.07, -0.29]}
              scale={[0.09, 0.34, 0.36]}
            />
            <mesh
              geometry={nodes.큐브006.geometry}
              material={materials["매테리얼.026"]}
              position={[-3.3, 3.35, -2.74]}
              rotation={[Math.PI, -0.04, 0]}
              scale={[0.09, 0.34, 0.36]}
            />
            <mesh
              geometry={nodes.큐브007.geometry}
              material={materials["매테리얼.027"]}
              position={[-3.49, 3.35, -2.73]}
              rotation={[Math.PI, -0.04, 0]}
              scale={[0.09, 0.34, 0.36]}
            />
            <mesh
              geometry={nodes.큐브008.geometry}
              material={materials["매테리얼.028"]}
              position={[-3.22, 3.42, -2.79]}
              rotation={[Math.PI, -0.04, Math.PI]}
              scale={[0.42, 0.45, 0.36]}
            />
            <mesh
              geometry={nodes.평면016.geometry}
              material={materials["매테리얼.017"]}
              position={[-3.11, 3.67, -2.75]}
              rotation={[-3.14, -0.07, 2.85]}
              scale={[0.09, 0.36, 0.3]}
            />
            <mesh
              geometry={nodes.평면017.geometry}
              material={materials["매테리얼.022"]}
              position={[-3.3, 3.68, -2.75]}
              rotation={[Math.PI, -0.04, Math.PI]}
              scale={[0.09, 0.36, 0.3]}
            />
            <mesh
              geometry={nodes.평면018.geometry}
              material={materials["매테리얼.023"]}
              position={[-3.49, 3.68, -2.74]}
              rotation={[Math.PI, -0.04, Math.PI]}
              scale={[0.09, 0.36, 0.3]}
            />
            <mesh
              geometry={nodes.평면019.geometry}
              material={materials["매테리얼.024"]}
              position={[-2.2, 2.96, -2.37]}
              rotation={[Math.PI, -0.04, Math.PI]}
              scale={[1.62, 0.63, 0.92]}
            />
            {/* 책상 1 끝 */}
          </>
        );
      case "2":
        return (
          <>
            {" "}
            {/* 책상2 */}
            <mesh
              geometry={nodes.desk2.geometry}
              material={materials["writing_desk.001"]}
              position={[-2.09, 2.88, -2.23]}
              rotation={[-1.58, 0, 0]}
              scale={0.81}
            />
            {/* 책상 2 끝 */}
          </>
        );
      case "3":
        return (
          <>
            {" "}
            <group position={[-2.14, 2.91, -2.08]} scale={[1.53, 0.43, 0.38]}>
              <mesh
                geometry={nodes.평면024_1.geometry}
                material={materials["매테리얼.040"]}
              />
              <mesh
                geometry={nodes.평면024_2.geometry}
                material={materials["매테리얼.041"]}
              />
            </group>
            <group
              position={[-2.14, 2.57, -0.45]}
              rotation={[-Math.PI / 2, 0, 2.44]}
              scale={0.09}
            >
              <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  geometry={nodes.back2_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                />
                <mesh
                  geometry={nodes.back_bone_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                />
                <mesh
                  geometry={nodes.adjustment_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                />
                <mesh
                  geometry={nodes.Bolt_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                  position={[-1.7, -9.01, -0.19]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[0.19, 0.05, 0.19]}
                />
                <mesh
                  geometry={nodes.Bolt1_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                  position={[-1.38, -9.26, -1.91]}
                  rotation={[0, 0, 1.44]}
                  scale={[0.12, 0.06, 0.12]}
                />
                <mesh
                  geometry={nodes.Bolt2_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                  position={[0.62, -9.26, -1.91]}
                  rotation={[0, 0, 1.69]}
                  scale={[0.12, 0.06, 0.12]}
                />
                <mesh
                  geometry={nodes.Bolt3_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                  position={[0.97, -9.01, -0.19]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[0.19, 0.05, 0.19]}
                />
                <mesh
                  geometry={nodes.pCube6_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                  position={[1.12, -9.45, 1.61]}
                  rotation={[0.78, -0.04, 2.35]}
                  scale={[0.03, 1.25, 0.74]}
                />
                <mesh
                  geometry={nodes.pCube9_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                />
                <mesh
                  geometry={nodes.pCylinder10_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                  position={[-0.44, -9.59, 1.61]}
                  rotation={[-0.17, 0, 0]}
                  scale={0.65}
                />
                <mesh
                  geometry={nodes.pCylinder14_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                  position={[-0.72, -0.43, -2]}
                  rotation={[2.97, 0, 0]}
                  scale={-1}
                />
                <mesh
                  geometry={nodes.polySurface11_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                  position={[-0.19, 0.08, 0.36]}
                  scale={[1.96, 1, 1]}
                />
                <mesh
                  geometry={nodes.pPlane3_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                />
                <mesh
                  geometry={nodes.butt_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                />
                <mesh
                  geometry={nodes.L_handle_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                />
                <mesh
                  geometry={nodes.R_handle_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                  position={[-0.76, 0, 0]}
                  rotation={[-Math.PI, 0, 0]}
                  scale={-1}
                />
                <mesh
                  geometry={nodes.polySurface24_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                />
                <mesh
                  geometry={nodes.polySurface43_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                />
                <mesh
                  geometry={nodes.wheel_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                />
                <mesh
                  geometry={nodes.wheel2_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                  position={[0.32, 0, -1.27]}
                  rotation={[0, 1.57, 0]}
                />
                <mesh
                  geometry={nodes.wheel3_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                  position={[-1.27, 0, -0.32]}
                  rotation={[0, -1.57, 0]}
                />
                <mesh
                  geometry={nodes.wheel4_aiStandardSurface1_0.geometry}
                  material={materials.aiStandardSurface1}
                  position={[-0.96, 0, -1.59]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                />
              </group>
            </group>
            <mesh
              geometry={nodes.큐브024.geometry}
              material={nodes.큐브024.material}
              position={[-2.33, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브025.geometry}
              material={nodes.큐브025.material}
              position={[-2.24, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브026.geometry}
              material={nodes.큐브026.material}
              position={[-2.14, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브027.geometry}
              material={nodes.큐브027.material}
              position={[-2.05, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브028.geometry}
              material={nodes.큐브028.material}
              position={[-1.97, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브029.geometry}
              material={nodes.큐브029.material}
              position={[-2.73, 2.98, -1.94]}
              rotation={[0.04, 0, 0]}
              scale={[0.08, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브030.geometry}
              material={nodes.큐브030.material}
              position={[-2.59, 2.98, -1.94]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브031.geometry}
              material={nodes.큐브031.material}
              position={[-2.51, 2.98, -1.94]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브032.geometry}
              material={nodes.큐브032.material}
              position={[-2.42, 2.98, -1.94]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브033.geometry}
              material={nodes.큐브033.material}
              position={[-2.32, 2.98, -1.94]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브034.geometry}
              material={nodes.큐브034.material}
              position={[-2.23, 2.98, -1.94]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브035.geometry}
              material={nodes.큐브035.material}
              position={[-2.14, 2.98, -1.94]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브036.geometry}
              material={nodes.큐브036.material}
              position={[-2.05, 2.98, -1.94]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브037.geometry}
              material={nodes.큐브037.material}
              position={[-2.78, 2.97, -1.85]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브038.geometry}
              material={nodes.큐브038.material}
              position={[-1.9, 2.98, -1.94]}
              rotation={[0.04, 0, 0]}
              scale={[0.09, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브039.geometry}
              material={nodes.큐브039.material}
              position={[-1.86, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.05, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브040.geometry}
              material={nodes.큐브040.material}
              position={[-2.59, 2.97, -1.85]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브041.geometry}
              material={nodes.큐브041.material}
              position={[-2.51, 2.97, -1.85]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브042.geometry}
              material={materials["매테리얼.032"]}
              position={[-2.28, 2.97, -1.85]}
              rotation={[0.04, 0, 0]}
              scale={[0.17, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브043.geometry}
              material={nodes.큐브043.material}
              position={[-1.95, 2.97, -1.85]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브044.geometry}
              material={nodes.큐브044.material}
              position={[-1.85, 2.97, -1.85]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브045.geometry}
              material={nodes.큐브045.material}
              position={[-2.05, 2.97, -1.85]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브046.geometry}
              material={materials["매테리얼.032"]}
              position={[-1.61, 2.97, -1.85]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브047.geometry}
              material={nodes.큐브047.material}
              position={[-2.69, 2.97, -1.85]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브048.geometry}
              material={materials["매테리얼.032"]}
              position={[-1.69, 2.97, -1.85]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브049.geometry}
              material={materials["매테리얼.032"]}
              position={[-1.53, 2.97, -1.85]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브050.geometry}
              material={materials["매테리얼.032"]}
              position={[-1.61, 2.97, -1.93]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브051.geometry}
              material={nodes.큐브051.material}
              position={[-1.71, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브052.geometry}
              material={nodes.큐브052.material}
              position={[-1.62, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브053.geometry}
              material={nodes.큐브053.material}
              position={[-1.53, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브054.geometry}
              material={nodes.큐브054.material}
              position={[-1.71, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브055.geometry}
              material={nodes.큐브055.material}
              position={[-1.62, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브056.geometry}
              material={nodes.큐브056.material}
              position={[-1.53, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브057.geometry}
              material={materials["매테리얼.032"]}
              position={[-2.77, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브058.geometry}
              material={materials["매테리얼.032"]}
              position={[-2.69, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브059.geometry}
              material={materials["매테리얼.032"]}
              position={[-2.6, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브060.geometry}
              material={materials["매테리얼.032"]}
              position={[-2.51, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브061.geometry}
              material={materials["매테리얼.032"]}
              position={[-2.42, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브062.geometry}
              material={materials["매테리얼.032"]}
              position={[-2.33, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브063.geometry}
              material={materials["매테리얼.032"]}
              position={[-2.24, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브064.geometry}
              material={materials["매테리얼.032"]}
              position={[-2.14, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브065.geometry}
              material={materials["매테리얼.032"]}
              position={[-2.05, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브066.geometry}
              material={materials["매테리얼.032"]}
              position={[-1.97, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브067.geometry}
              material={materials["매테리얼.032"]}
              position={[-1.88, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브068.geometry}
              material={materials["매테리얼.032"]}
              position={[-1.79, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브069.geometry}
              material={materials["매테리얼.032"]}
              position={[-1.71, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브070.geometry}
              material={materials["매테리얼.032"]}
              position={[-1.62, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브071.geometry}
              material={materials["매테리얼.032"]}
              position={[-1.53, 2.99, -2.24]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브072.geometry}
              material={materials["매테리얼.034"]}
              position={[-2.14, 3.69, -2.72]}
              rotation={[0, 0, -Math.PI]}
              scale={[-0.8, -0.57, -0.02]}
            />
            <mesh
              geometry={nodes.큐브073.geometry}
              material={materials["매테리얼.035"]}
              position={[-2.14, 3.09, -2.98]}
              scale={[0.09, 0.18, 0.09]}
            />
            <mesh
              geometry={nodes.큐브074.geometry}
              material={materials["매테리얼.036"]}
              position={[-0.99, 2.96, -2.04]}
              scale={[0.11, 0.06, 0.15]}
            />
            <group position={[-1.02, 1.6, -2.43]} scale={[0.31, 0.53, 0.49]}>
              <mesh
                geometry={nodes.큐브075_1.geometry}
                material={materials["매테리얼.037"]}
              />
              <mesh
                geometry={nodes.큐브075_2.geometry}
                material={materials["매테리얼.038"]}
              />
            </group>
            <group position={[-3.36, 3.26, -2.92]} scale={[0.24, 0.33, 0.34]}>
              <mesh
                geometry={nodes.큐브076_1.geometry}
                material={materials["매테리얼.031"]}
              />
              <mesh
                geometry={nodes.큐브076_2.geometry}
                material={materials["매테리얼.039"]}
              />
            </group>
            <mesh
              geometry={nodes.평면.geometry}
              material={materials["매테리얼.030"]}
              position={[-2.14, 2.77, -2.43]}
              scale={[1.7, 0.77, 0.85]}
            />
            <mesh
              geometry={nodes.평면020.geometry}
              material={materials["매테리얼.031"]}
              position={[-0.44, 1.92, -2.43]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.85, 0.77, 0.85]}
            />
            <mesh
              geometry={nodes.평면021.geometry}
              material={materials["매테리얼.031"]}
              position={[-3.84, 1.92, -2.43]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.85, 0.77, 0.85]}
            />
            <mesh
              geometry={nodes.평면022.geometry}
              material={materials["매테리얼.033"]}
              position={[-2.14, 2.93, -2.04]}
              scale={[0.75, 0.59, 0.28]}
            />
            {/* 책상 3 시작 */}
            <mesh
              geometry={nodes.구체005.geometry}
              material={nodes.구체005.material}
              position={[-0.99, 3, -2.1]}
              rotation={[-0.31, 0, 0]}
              scale={[0.01, 0.02, 0.02]}
            />
            <mesh
              geometry={nodes.구체006.geometry}
              material={nodes.구체006.material}
              position={[-1.02, 1.41, -1.94]}
              scale={[-0.06, -0.06, -0.01]}
            />
            <mesh
              geometry={nodes.베지어커브.geometry}
              material={nodes.베지어커브.material}
              position={[-0.87, 2.91, -2.72]}
              scale={0.43}
            />
            <mesh
              geometry={nodes.베지어커브001.geometry}
              material={materials["매테리얼.035"]}
              position={[-1.95, 2.91, -2.9]}
              scale={0.43}
            />
            <mesh
              geometry={nodes.베지어커브002.geometry}
              material={nodes.베지어커브002.material}
              position={[-1.95, 3.39, -3.5]}
              scale={0.43}
            />
            <mesh
              geometry={nodes.큐브009.geometry}
              material={nodes.큐브009.material}
              position={[-2.75, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.06, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브010.geometry}
              material={nodes.큐브010.material}
              position={[-2.77, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브011.geometry}
              material={nodes.큐브011.material}
              position={[-2.63, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브012.geometry}
              material={nodes.큐브012.material}
              position={[-2.54, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브013.geometry}
              material={nodes.큐브013.material}
              position={[-2.45, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브014.geometry}
              material={nodes.큐브014.material}
              position={[-2.36, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브015.geometry}
              material={nodes.큐브015.material}
              position={[-2.27, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브016.geometry}
              material={nodes.큐브016.material}
              position={[-2.18, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브017.geometry}
              material={nodes.큐브017.material}
              position={[-2.09, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브018.geometry}
              material={nodes.큐브018.material}
              position={[-2, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브019.geometry}
              material={nodes.큐브019.material}
              position={[-1.88, 2.99, -2.04]}
              rotation={[0.04, 0, 0]}
              scale={[0.07, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브020.geometry}
              material={nodes.큐브020.material}
              position={[-2.69, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브021.geometry}
              material={nodes.큐브021.material}
              position={[-2.6, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브022.geometry}
              material={nodes.큐브022.material}
              position={[-2.51, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              geometry={nodes.큐브023.geometry}
              material={nodes.큐브023.material}
              position={[-2.42, 2.99, -2.14]}
              rotation={[0.04, 0, 0]}
              scale={[0.03, 0.02, 0.03]}
            />
            {/* 책상 3 끝 */}
          </>
        );
    }
  };

  const selectBed = () => {
    switch (itemStatus?.bed) {
      case "1":
        return (
          <>
            {/* 침대 1 */}
            <mesh
              geometry={nodes.구체.geometry}
              material={materials["매테리얼.002"]}
              position={[0.8, 3.32, 0.69]}
              scale={0.27}
            />
            <mesh
              geometry={nodes.평면003.geometry}
              material={materials["매테리얼.005"]}
              position={[2.14, 2.19, -1.23]}
              scale={[1.24, 2.03, 2.03]}
            />
            <mesh
              geometry={nodes.평면004.geometry}
              material={materials["매테리얼.003"]}
              position={[2.14, 0.87, -1.23]}
              scale={3.9}
            />
            <mesh
              geometry={nodes.평면005.geometry}
              material={materials["매테리얼.001"]}
              position={[0.79, 1.05, 0.69]}
              scale={[-0.12, -0.2, -0.12]}
            />
            <mesh
              geometry={nodes.평면006.geometry}
              material={nodes.평면006.material}
              position={[2.14, 2.48, -1.23]}
              scale={[1.24, 2.03, 1.66]}
            />
            <mesh
              geometry={nodes.평면007.geometry}
              material={materials.매테리얼}
              position={[2.14, 2.48, -1]}
              scale={[1.24, 2.03, 2.05]}
            />
            <mesh
              geometry={nodes.평면008.geometry}
              material={materials["매테리얼.004"]}
              position={[2.14, 2.68, -2.51]}
              scale={[0.46, 1.45, 0.28]}
            />
            {/* 침대 1 끝 */}
          </>
        );
      case "2":
        return (
          <>
            {" "}
            {/* 침대 2 시작 */}
            <mesh
              geometry={nodes.실린더003.geometry}
              material={materials["매테리얼.042"]}
              position={[3.46, 2.27, -3.25]}
              rotation={[0, 1.57, 0]}
              scale={0.08}
            />
            <mesh
              geometry={nodes.실린더004.geometry}
              material={materials["매테리얼.042"]}
              position={[3.09, 2.27, -3.25]}
              rotation={[0, 1.57, 0]}
              scale={0.06}
            />
            <mesh
              geometry={nodes.실린더005.geometry}
              material={materials["매테리얼.042"]}
              position={[2.72, 2.27, -3.25]}
              rotation={[0, 1.57, 0]}
              scale={0.06}
            />
            <mesh
              geometry={nodes.실린더006.geometry}
              material={materials["매테리얼.042"]}
              position={[1.72, 1.51, 0.97]}
              rotation={[0, 1.57, 0]}
              scale={[0.1, 0.51, 0.11]}
            />
            <mesh
              geometry={nodes.실린더007.geometry}
              material={materials["매테리얼.046"]}
              position={[1.79, 1.91, -0.39]}
              rotation={[0, 1.57, 0]}
              scale={0.09}
            />
            <mesh
              geometry={nodes.큐브077.geometry}
              material={materials["매테리얼.042"]}
              position={[2.54, 1.98, -0.98]}
              rotation={[0, 1.57, 0]}
              scale={[2.38, 0.07, 1.08]}
            />
            <mesh
              geometry={nodes.큐브078.geometry}
              material={materials["매테리얼.043"]}
              position={[2.54, 2.2, -0.98]}
              rotation={[0, 1.57, 0]}
              scale={[2.33, 0.07, 1.08]}
            />
            <mesh
              geometry={nodes.큐브079.geometry}
              material={materials["매테리얼.043"]}
              position={[2.54, 2.42, -0.98]}
              rotation={[0, 1.57, 0]}
              scale={[2.33, 0.07, 1.08]}
            />
            <mesh
              geometry={nodes.큐브080.geometry}
              material={materials["매테리얼.044"]}
              position={[2.54, 2.62, -2.66]}
              rotation={[0, 1.57, 0]}
              scale={[0.24, 0.13, 0.37]}
            />
            <mesh
              geometry={nodes.평면024.geometry}
              material={materials["매테리얼.045"]}
              position={[2.54, 2.56, -0.98]}
              rotation={[0, 1.57, 0]}
              scale={[1.25, 0.63, 1.1]}
            />
            <mesh
              geometry={nodes.평면025.geometry}
              material={materials["매테리얼.045"]}
              position={[3.65, 2.33, -0.98]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.25, 0.63, 0.22]}
            />
            <mesh
              geometry={nodes.평면026.geometry}
              material={materials["매테리얼.047"]}
              position={[2.54, 3.27, -0.38]}
              rotation={[0, 1.57, 0]}
              scale={[0.63, 0.63, 1.01]}
            />
            {/* 침대 2 끝 */}
          </>
        );
      case "3":
        return (
          <>
            {" "}
            {/* 침대 3 시작 */}
            <group
              position={[3.12, -0.53, -3.21]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.84}
            >
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group
                  position={[-124.18, 216.14, 292.05]}
                  rotation={[-Math.PI / 2, 0, -3.13]}
                  scale={[101.87, 92.58, 92.58]}
                >
                  <group
                    position={[-0.04, 0.43, -0.03]}
                    scale={[1.36, 0.92, 0.91]}
                  >
                    <mesh
                      geometry={nodes.BedSheet_Material005_0.geometry}
                      material={materials["Material.005"]}
                    />
                    <mesh
                      geometry={nodes.BedSheet_Material006_0.geometry}
                      material={materials["Material.006"]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Bed_Material002_0.geometry}
                    material={materials["Material.002"]}
                  />
                  <mesh
                    geometry={nodes.Bed_Material003_0.geometry}
                    material={materials["Material.003"]}
                  />
                  <mesh
                    geometry={nodes.BedInner_Material003_0.geometry}
                    material={materials["Material.003"]}
                    position={[0, 0, -0.14]}
                    scale={[1.25, 1, 1]}
                  />
                  <mesh
                    geometry={nodes.BedPillow_Material004_0.geometry}
                    material={materials["Material.004"]}
                    position={[-0.31, -2.59, 1.75]}
                    rotation={[0.45, 0, 0]}
                    scale={[0.82, 0.26, 0.57]}
                  />
                </group>
              </group>
            </group>
          </>
        );
    }
  };
  const selectLamp = () => {
    switch (itemStatus?.lamp) {
      case "1":
        return (
          <>
            {/* 조명 1 */}
            <group
              position={[-0.3, 1.01, -1.35]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={4.7}
            >
              <group rotation={[Math.PI / 2, 0, 0]}>
                <group scale={0.14}>
                  <mesh
                    geometry={nodes.Object_4002.geometry}
                    material={materials[".001"]}
                    position={[0.64, 0.17, -1.14]}
                    scale={0.5}
                  />
                  <mesh
                    geometry={nodes.Object_8001.geometry}
                    material={materials[".002"]}
                    position={[0.64, 0.17, -1.14]}
                    scale={0.5}
                  />
                </group>
              </group>
            </group>
            {/* 조명 1 끝 */}
          </>
        );
      case "2":
        return (
          <>
            {" "}
            {/* 조명 2 시작 */}
            <mesh
              geometry={nodes.구체008.geometry}
              material={materials["매테리얼.054"]}
              position={[0.75, 4.05, -2.39]}
              scale={0.14}
            />
            <mesh
              geometry={nodes.실린더008.geometry}
              material={materials["매테리얼.053"]}
              position={[0.1, 2, -2.41]}
              scale={0.03}
              onClick={() => setIsLamp((prev) => !prev)}
            />
            <mesh
              geometry={nodes.원뿔.geometry}
              material={materials["매테리얼.052"]}
              position={[0.63, 4.24, -2.39]}
              rotation={[0, 0, 0.52]}
              scale={0.27}
              onClick={() => setIsLamp((prev) => !prev)}
            />
            <mesh
              geometry={nodes.평면027.geometry}
              material={materials["매테리얼.051"]}
              position={[0.1, 1.13, -2.41]}
              scale={0.47}
              onClick={() => setIsLamp((prev) => !prev)}
            />
            {/* 조명 2 끝 */}
          </>
        );
    }
  };
  const selectEtc = () => {
    switch (itemStatus?.etc) {
      case "1":
        return (
          <>
            <group
              position={[2.38, 0.96, 2.95]}
              rotation={[-Math.PI / 2, 0, -1.85]}
              scale={0.41}
            >
              <mesh
                geometry={nodes.Object_10.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_11.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_12.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_13.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_14.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_15.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_16.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_17.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_18.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_19.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_2001.geometry}
                material={materials["Material.040"]}
              />
              <mesh
                geometry={nodes.Object_20.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_21.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_22.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_23.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_24.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_25.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_26.geometry}
                material={materials["Material.046"]}
              />
              <mesh
                geometry={nodes.Object_3001.geometry}
                material={materials["Material.040"]}
              />
              <mesh
                geometry={nodes.Object_4001.geometry}
                material={materials["Material.041"]}
              />
              <mesh
                geometry={nodes.Object_5001.geometry}
                material={materials["Material.042"]}
              />
              <mesh
                geometry={nodes.Object_6001.geometry}
                material={materials["Material.043"]}
              />
              <mesh
                geometry={nodes.Object_7.geometry}
                material={materials["Material.044"]}
              />
              <mesh
                geometry={nodes.Object_8.geometry}
                material={materials["Material.045"]}
              />
              <mesh
                geometry={nodes.Object_9.geometry}
                material={materials["Material.046"]}
              />
            </group>
          </>
        );
      case "2":
        return (
          <>
            {/* 기타 3 */}
            <mesh
              geometry={nodes.구체001.geometry}
              material={nodes.구체001.material}
              position={[1.3, 1.92, 3.13]}
              rotation={[0, -1.57, 0]}
              scale={0.06}
            />
            <mesh
              geometry={nodes.구체002.geometry}
              material={nodes.구체002.material}
              position={[0.76, 1.46, 3.13]}
              rotation={[0, -1.57, 0]}
              scale={0.06}
            />
            <mesh
              geometry={nodes.구체003.geometry}
              material={materials["매테리얼.008"]}
              position={[2.53, 3.9, 3.05]}
              rotation={[0, -1.57, 0]}
              scale={0.34}
            />
            <mesh
              geometry={nodes.실린더.geometry}
              material={materials["매테리얼.007"]}
              position={[2.41, 3.27, 3.04]}
              rotation={[0, -1.57, 0]}
              scale={0.5}
            />
            <mesh
              geometry={nodes.평면009.geometry}
              material={materials["매테리얼.009"]}
              position={[2.47, 2.12, 3.13]}
              rotation={[0, -1.57, 0]}
              scale={[0.88, 2.7, 0.97]}
            />
            <mesh
              geometry={nodes.평면010.geometry}
              material={materials["매테리얼.010"]}
              position={[1.64, 1.96, 2.37]}
              rotation={[0, -1.57, 0]}
              scale={[0.16, 3.13, 0.18]}
            />
            {/* 기타 3 끝 */}
          </>
        );
      case "3":
        return (
          <>
            {" "}
            <group
              position={[2.73, 0.9, 3.06]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={0.04}
            >
              <group position={[-44.67, -17.64, 0]}>
                <mesh
                  geometry={nodes.Object_3.geometry}
                  material={materials.Material__7}
                  position={[15.29, 0, 0]}
                  scale={[0.72, 1.1, 1.1]}
                />
                <mesh
                  geometry={nodes.Object_4.geometry}
                  material={materials.Material__7}
                  position={[15.29, 0, 0]}
                  scale={[0.72, 1.1, 1.1]}
                />
                <mesh
                  geometry={nodes.Object_5.geometry}
                  material={materials.Material__7}
                  position={[15.29, 0, 0]}
                  scale={[0.72, 1.1, 1.1]}
                />
                <mesh
                  geometry={nodes.Object_6.geometry}
                  material={materials.Material__7}
                  position={[15.29, 0, 0]}
                  scale={[0.72, 1.1, 1.1]}
                />
              </group>
            </group>
          </>
        );
    }
  };

  const [isLamp, setIsLamp] = useState(false);

  const [isLight, setIsLight] = useState(true);

  const props: any = { position };
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        {isLamp && <pointLight position={[3, 3.05, -2.39]} intensity={0.4} />}{" "}
        {isLight && (
          // <directionalLight intensity={0.7} castShadow position={[-50, 50, 50]} />
          <pointLight castShadow position={[-15, 15, 15]} power={8} />
        )}
        {/*  기본방 */}{" "}
        <mesh
          geometry={nodes.평면028.geometry}
          material={nodes.평면028.material}
          position={[4.27, 5.34, 4.14]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.32, 0.69, 0.26]}
          onClick={() => setIsLight((prev) => !prev)}
        />
        <mesh
          geometry={nodes.실린더001.geometry}
          material={materials["매테리얼.011"]}
          position={[-0.33, 5.58, -3.24]}
          scale={0.2}
        >
          <mesh
            geometry={nodes.구체004_1.geometry}
            material={materials["매테리얼.012"]}
            position={[0, 1.62, 0]}
            scale={[1.26, 2.18, 1.26]}
          />
        </mesh>
        <mesh
          geometry={nodes.큐브.geometry}
          material={materials["매테리얼.021"]}
          position={[0.06, 0.87, 0.41]}
          scale={4.21}
        />
        <mesh
          geometry={nodes.큐브001.geometry}
          material={materials["매테리얼.016"]}
          position={[1.92, 2.69, -0.25]}
          scale={[2.39, 1.32, 0.55]}
        />
        <mesh
          geometry={nodes.큐브004.geometry}
          material={materials["매테리얼.013"]}
          position={[0.06, 0.87, 0.41]}
          scale={4.21}
        />
        <mesh
          geometry={nodes.평면001.geometry}
          material={nodes.평면001.material}
          position={[0.06, 0.87, 0.41]}
          scale={4.21}
        />
        <mesh
          geometry={nodes.평면002.geometry}
          material={materials["매테리얼.006"]}
          position={[2.33, 0.92, 0.41]}
          scale={[6.48, 4.21, 4.21]}
        />
        <mesh
          geometry={nodes.평면011.geometry}
          material={materials["매테리얼.015"]}
          position={[-1.78, 5.4, -3.31]}
          rotation={[0, -0.41, 0]}
          scale={[0.25, 0.33, 0.33]}
        />
        <mesh
          geometry={nodes.평면012.geometry}
          material={materials["매테리얼.014"]}
          position={[-1.78, 5.49, -3.31]}
          rotation={[0, -0.01, 0]}
          scale={[0.25, 0.33, 0.33]}
        />
        <mesh
          geometry={nodes.평면013.geometry}
          material={materials["매테리얼.018"]}
          position={[4.21, 3.74, -0.25]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.58, 0.49, 0.53]}
        />
        <mesh
          geometry={nodes.평면014.geometry}
          material={materials["매테리얼.018"]}
          position={[4.21, 4.14, 0.8]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.3, 0.3, 0.32]}
        />
        <mesh
          geometry={nodes.평면015.geometry}
          material={materials["매테리얼.018"]}
          position={[4.21, 3.36, 0.8]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.3, 0.3, 0.32]}
        />
        <mesh
          geometry={nodes.큐브002.geometry}
          material={materials["매테리얼.020"]}
          position={[1.92, 3.67, 0.8]}
          scale={[2.39, 0.62, 0.35]}
        />
        <mesh
          geometry={nodes.큐브003.geometry}
          material={materials["매테리얼.019"]}
          position={[1.92, 2.86, 0.8]}
          scale={[2.39, 0.62, 0.35]}
        />
      </group>
      {/* 함수 써주기 */}
      {selectTable()}
      {selectLamp()}
      {selectBed()}
      {selectEtc()}
    </group>
  );
}

useGLTF.preload("/MiniRoom/miniroomBetaFinal.glb");
